---
- hosts: all
  tasks:

  - name: Assign IP address to loopback
    command: ip addr add {{ loopback_ip }} dev lo
    when: hostvars[inventory_hostname]['ansible_lo']['ipv4_secondaries'] is not defined
    become: true

  - name: Assign loopback IP to all interfaces
    command: ip addr add {{ loopback_ip }} dev {{ item }}
    with_items: '{{ansible_interfaces}}'
    when: item != "lo" and item != "eth0" and ansible_{{item}}['active']
    become: true

  - name: Enable OSPF and Zebra daemons
    replace: dest=/etc/quagga/daemons regexp='(ospfd|zebra)=no' replace='\1=yes' backup=yes
    become: true

  - name: Restart quagga
    service: name=quagga state=restarted
    become: true

  - name: Assign router-id
    command: cl-ospf router-id set {{ loopback_ip }}
    become: true

  - name: Enable OSPF on all front panel ports
    command: cl-ospf interface set {{ item[1] }} {{ item[0] }}
    with_nested:
      - [ "network point-to-point", "area 0.0.0.0" ]
      - '{{ansible_interfaces}}'
    when: item[1] != "lo" and item[1] != "eth0" and ansible_{{ item[1] }}['active']
    become: true

  - name: Add loopback interface so those routes get announced
    command: "{{ item }}"
    with_items:
      - cl-ospf interface set lo passive
      - cl-ospf interface set lo area 0.0.0.0
    become: true

  - name: Save configuration to file
    command: cl-rctl write-config
    become: true

